[tool.poetry]
name = "mindbox-second-task"
version = "0.1.0"
description = ""
authors = ["dkrvns <danila.krn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.40"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
